class_name UITheme
extends RefCounted
## Builds the game's Theme. Run through `tools/bake_theme.gd`, which writes the
## result to `resources/ui/bog_theme.tres`; the scenes reference that file.
##
## Why generated rather than hand-authored? A Theme for this many controls is
## roughly forty `StyleBoxFlat` sub-resources, and as a `.tres` that is forty
## anonymous blocks of numbers that no diff can explain and no one can comment.
## The same argument the animation graph is built in code for (see
## `BogAnimator`) applies twice over here: written this way, "focus is a
## one-pixel amber ring, everywhere, on everything" is one function instead of
## nine identical blocks that will eventually disagree with each other.
##
## The baked `.tres` is committed, so the editor previews the real thing and a
## fresh clone needs no build step. Do not edit that file by hand — re-bake:
##
##     Godot --headless --path . --script tools/bake_theme.gd
##
## **The look is Quiet**, chosen off the showroom (`tools/showroom/`): editorial
## rather than gamey, air and typography instead of chrome. Three rules run
## through everything below, and every stylebox here is one of them:
##
## 1. **No borders.** A shape is its fill. The only strokes left in the UI are
##    the ones that *mean* something — the focus ring, the nav underline, the
##    rule under a text field, the primary button's outline.
## 2. **Surfaces are white at an alpha**, not a lighter blue. So a panel reads as
##    the scene behind it, dimmed, over the forest and over the arena alike.
## 3. **One accent** (`UIPalette.AMBER`, which is `BOG`), and where it is a fill
##    rather than a line it is a wash at `PRESS_WASH` alpha. Hover lightens the
##    surface; pressing it tints the surface yellow. That pair is the whole
##    interaction vocabulary, and it is the same on a button, a dropdown row and
##    a ghost.

## Windows-first, as the export preset is (PLAN 7.1).
##
## **The Light weight is asked for as a weight, not as a family.** Windows hands
## Godot the family "Segoe UI Variable Display" and the named instances are
## reached through `font_weight`; a `SystemFont` asking for the face "Segoe UI
## Light" silently falls through to Regular, which is how the showroom's first
## Quiet render came back looking like every other candidate. The face list keeps
## the Light names first anyway — they cost nothing and a machine that *does*
## resolve them gets the right thing without the variable axis — and
## `DISPLAY_WEIGHT` is what actually does the work. `allow_system_fallback`
## covers a machine with none of them installed.
const DISPLAY_FACES: PackedStringArray = [
	"Segoe UI Variable Display Light", "Segoe UI Light", "Segoe UI",
]
const BODY_FACES: PackedStringArray = [
	"Segoe UI Variable Text", "Segoe UI", "Noto Sans",
]
const DISPLAY_WEIGHT := 300

## `spacing_glyph`, in pixels per glyph. A section label is four dim words and
## nothing else, and tracking is the only thing that tells the eye it is a label
## rather than a sentence; the wordmark is one word at 72 px and wants more.
const TRACKING_SECTION := 6
const TRACKING_DISPLAY := 8

## The accent as a fill is always a wash at this alpha — pressed buttons, the
## hovered row of a dropdown. A solid yellow block is reserved for the one
## primary button on a screen, and using the same solid anywhere else would cost
## that button the only thing it has.
const PRESS_WASH := 0.18

## Button padding. `PAD_X`/`PAD_Y` is the ordinary button; the primary is a step
## larger, and the small controls (fields, dropdowns) state their own.
const PAD_X := 20
const PAD_Y := 10


## The one entry point. Everything below is private detail.
static func build() -> Theme:
	var theme := Theme.new()
	theme.resource_name = "BOG UI (generated by tools/bake_theme.gd - do not hand-edit)"

	var body := _system_font(BODY_FACES, 400)
	var display := _system_font(DISPLAY_FACES, DISPLAY_WEIGHT)
	# Tracked-out display face. Wide letter spacing is what makes a short
	# all-caps label read as a heading rather than as shouting.
	var tracked := _tracked(display, TRACKING_SECTION)
	var tracked_display := _tracked(display, TRACKING_DISPLAY)

	theme.default_font = body
	theme.default_font_size = UIPalette.FONT_BODY

	_labels(theme, display, tracked, tracked_display)
	_panels(theme)
	_buttons(theme, display)
	_inputs(theme, body)
	_toggles(theme, body)
	_sliders(theme)
	_scrollbars(theme)
	_misc(theme, body)
	return theme


# ------------------------------------------------------------------ pieces ---

static func _system_font(faces: PackedStringArray, weight: int) -> SystemFont:
	var font := SystemFont.new()
	font.font_names = faces
	font.allow_system_fallback = true
	font.font_weight = weight
	# The UI is drawn at whole-pixel sizes and scaled by the viewport, so
	# subpixel positioning buys nothing and costs glyph-cache entries.
	font.subpixel_positioning = TextServer.SUBPIXEL_POSITIONING_DISABLED
	return font


static func _tracked(base: Font, spacing: int) -> FontVariation:
	var variation := FontVariation.new()
	variation.base_font = base
	variation.spacing_glyph = spacing
	return variation


static func _flat(bg: Color, radius: int = UIPalette.RADIUS) -> StyleBoxFlat:
	var box := StyleBoxFlat.new()
	box.bg_color = bg
	box.set_corner_radius_all(radius)
	return box


## A fill with a rule along one edge. The whole UI has exactly three of these —
## the nav underline, the text field, the primary button's outline — and they
## are the only strokes in it.
static func _ruled(bg: Color, rule: Color, width: int, side: Side,
		radius: int = UIPalette.RADIUS) -> StyleBoxFlat:
	var box := _flat(bg, radius)
	box.border_color = rule
	match side:
		SIDE_BOTTOM: box.border_width_bottom = width
		SIDE_TOP: box.border_width_top = width
		SIDE_LEFT: box.border_width_left = width
		SIDE_RIGHT: box.border_width_right = width
	return box


static func _outlined(bg: Color, border: Color, width: int,
		radius: int = UIPalette.RADIUS) -> StyleBoxFlat:
	var box := _flat(bg, radius)
	box.border_color = border
	box.set_border_width_all(width)
	return box


static func _pad(box: StyleBoxFlat, horizontal: int, vertical: int) -> StyleBoxFlat:
	box.content_margin_left = horizontal
	box.content_margin_right = horizontal
	box.content_margin_top = vertical
	box.content_margin_bottom = vertical
	return box


static func _clear() -> Color:
	return Color(0, 0, 0, 0)


## The accent as a surface rather than as a line.
static func _wash(colour: Color = UIPalette.AMBER, alpha: float = PRESS_WASH) -> Color:
	return UIPalette.at(colour, alpha)


# ------------------------------------------------------------------ labels ---

static func _labels(theme: Theme, display: Font, tracked: Font, tracked_display: Font) -> void:
	theme.set_color("font_color", "Label", UIPalette.TEXT)
	theme.set_font_size("font_size", "Label", UIPalette.FONT_BODY)

	# Display is the wordmark: enormous, tracked, Light, and used once per
	# screen. Everything else steps down from it.
	_label_variation(theme, "Display", tracked_display, UIPalette.FONT_DISPLAY, UIPalette.BOG)
	_label_variation(theme, "Head", display, UIPalette.FONT_HEAD, UIPalette.TEXT)
	_label_variation(theme, "Lead", display, UIPalette.FONT_LEAD, UIPalette.TEXT)
	# Section headings: small, tracked, dim. They label a panel without
	# competing with anything inside it.
	_label_variation(theme, "Section", tracked, UIPalette.FONT_TINY, UIPalette.TEXT_FAINT)
	_label_variation(theme, "Dim", null, UIPalette.FONT_BODY, UIPalette.TEXT_DIM)
	_label_variation(theme, "Small", null, UIPalette.FONT_SMALL, UIPalette.TEXT_DIM)
	_label_variation(theme, "Tiny", null, UIPalette.FONT_TINY, UIPalette.TEXT_FAINT)
	_label_variation(theme, "Accent", display, UIPalette.FONT_BODY, UIPalette.AMBER)
	# The unit under a slider (D-076). Accent, because it is the live value of
	# the control above it and live values are accent everywhere else; a step
	# smaller than body, because it is a caption on a control rather than a line
	# of the panel — the name in the left column is what the eye scans down, and
	# a unit set at the same size as that name competes with it on every row.
	_label_variation(theme, "Value", display, UIPalette.FONT_SMALL, UIPalette.AMBER)
	# Numbers the player reads under pressure: the clock, a score, a countdown.
	_label_variation(theme, "Readout", display, UIPalette.FONT_HEAD, UIPalette.TEXT)


static func _label_variation(theme: Theme, name: String, font: Font, size: int,
		colour: Color) -> void:
	var type := name + "Label"
	theme.set_type_variation(type, "Label")
	if font != null:
		theme.set_font("font", type, font)
	theme.set_font_size("font_size", type, size)
	theme.set_color("font_color", type, colour)


# ------------------------------------------------------------------ panels ---

## **No panel in this UI has a border.** The old scheme drew a hairline around
## every card, and at 1600x900 eight of those on one screen is a wireframe
## drawing of the layout rather than a layout. A panel is now a dimming of what
## is behind it and nothing else; the rounded corner is what says "this is a
## surface", which is why the radius went 4 -> 10 at the same time.
static func _panels(theme: Theme) -> void:
	theme.set_stylebox("panel", "Panel", _flat(UIPalette.PANEL))
	theme.set_stylebox("panel", "PanelContainer", _flat(UIPalette.PANEL))

	theme.set_type_variation("CardPanel", "PanelContainer")
	theme.set_stylebox("panel", "CardPanel",
		_pad(_flat(UIPalette.PANEL), UIPalette.PAD, UIPalette.PAD))

	theme.set_type_variation("RowPanel", "PanelContainer")
	# Deliberately tight: a full eight-player roster has to fit the lobby's list
	# without a scroll bar, and a scroll bar in a list of eight is a design that
	# has given up.
	theme.set_stylebox("panel", "RowPanel", _pad(_flat(UIPalette.RAISED), 14, 5))

	# The HUD has no 3D "behind" to preserve, because it *is* on top of the
	# game. Its panels are barely there at all: 40% of a near-black, where the
	# menu's panels are 72%.
	theme.set_type_variation("HudPanel", "PanelContainer")
	theme.set_stylebox("panel", "HudPanel",
		_pad(_flat(UIPalette.at(UIPalette.VOID, 0.40)), 14, 8))

	# The one square-cornered thing in the UI, because it is the screen rather
	# than a shape on it.
	theme.set_type_variation("ScrimPanel", "PanelContainer")
	theme.set_stylebox("panel", "ScrimPanel", _flat(UIPalette.at(UIPalette.VOID, 0.86), 0))


# ----------------------------------------------------------------- buttons ---

## Rest, hover, press: a 4% surface, an 8% surface, and the accent at 18%. That
## triple is the whole vocabulary, and `GhostButton`, `OptionButton` and a
## `PopupMenu` row below all speak it at their own padding so that pressing
## anything in this game feels like the same gesture.
static func _buttons(theme: Theme, display: Font) -> void:
	theme.set_font("font", "Button", display)
	theme.set_font_size("font_size", "Button", UIPalette.FONT_BODY)
	theme.set_color("font_color", "Button", UIPalette.TEXT)
	theme.set_color("font_hover_color", "Button", UIPalette.AMBER_GLOW)
	theme.set_color("font_pressed_color", "Button", UIPalette.AMBER)
	theme.set_color("font_focus_color", "Button", UIPalette.TEXT)
	theme.set_color("font_disabled_color", "Button", UIPalette.TEXT_FAINT)
	theme.set_stylebox("normal", "Button", _pad(_flat(UIPalette.RAISED), PAD_X, PAD_Y))
	theme.set_stylebox("hover", "Button", _pad(_flat(UIPalette.RAISED_STRONG), PAD_X, PAD_Y))
	theme.set_stylebox("pressed", "Button", _pad(_flat(_wash()), PAD_X, PAD_Y))
	# A disabled button is not a greyed-out box, it is an absent one: the label
	# goes to `TEXT_FAINT` and the surface goes away entirely, so a row of
	# buttons with one of them off has a hole in it rather than a dead tile.
	theme.set_stylebox("disabled", "Button", _pad(_flat(_clear()), PAD_X, PAD_Y))
	# One focus ring for the whole UI, so keyboard users get the same amber
	# outline on a button, a text field and a dropdown. It is drawn outside the
	# control rather than inside it, so gaining focus never shifts the layout.
	theme.set_stylebox("focus", "Button", _focus_ring())

	_primary(theme)
	_nav(theme)

	# Ghost: no surface at all until you touch it, for anything secondary — a
	# copy button, a back arrow. The same three states at a smaller padding.
	theme.set_type_variation("GhostButton", "Button")
	theme.set_font_size("font_size", "GhostButton", UIPalette.FONT_SMALL)
	theme.set_color("font_color", "GhostButton", UIPalette.TEXT_DIM)
	theme.set_color("font_hover_color", "GhostButton", UIPalette.TEXT)
	theme.set_stylebox("normal", "GhostButton", _pad(_flat(_clear()), 12, 7))
	theme.set_stylebox("hover", "GhostButton", _pad(_flat(UIPalette.RAISED_STRONG), 12, 7))
	theme.set_stylebox("pressed", "GhostButton", _pad(_flat(_wash()), 12, 7))
	theme.set_stylebox("disabled", "GhostButton", _pad(_flat(_clear()), 12, 7))

	# Danger: leaving, quitting. Red only on hover, because a permanently red
	# button among grey ones draws the eye to the one action nobody is hunting
	# for. It is the same wash the accent uses, in the one other colour the
	# palette has.
	theme.set_type_variation("DangerButton", "Button")
	theme.set_color("font_hover_color", "DangerButton", UIPalette.DANGER)
	theme.set_color("font_pressed_color", "DangerButton", UIPalette.DANGER)
	theme.set_stylebox("hover", "DangerButton",
		_pad(_flat(_wash(UIPalette.DANGER, 0.14)), PAD_X, PAD_Y))
	theme.set_stylebox("pressed", "DangerButton",
		_pad(_flat(_wash(UIPalette.DANGER, 0.26)), PAD_X, PAD_Y))


## Primary: at most one per screen, and **an outline rather than a fill**.
##
## The old scheme's primary was a solid amber block, which on a near-black
## screen with nothing else coloured was the loudest thing in the game by a wide
## margin — the eye went to START MATCH before it went to the match settings the
## button was there to confirm. As an outline it is still the only accent-shaped
## control on the screen, and it fills solid the moment you point at it, so the
## loud state is the one you asked for.
static func _primary(theme: Theme) -> void:
	const PX := PAD_X + 4
	const PY := PAD_Y + 1
	theme.set_type_variation("PrimaryButton", "Button")
	theme.set_color("font_color", "PrimaryButton", UIPalette.AMBER)
	theme.set_color("font_hover_color", "PrimaryButton", UIPalette.TEXT_ON_ACCENT)
	theme.set_color("font_pressed_color", "PrimaryButton", UIPalette.TEXT_ON_ACCENT)
	theme.set_color("font_focus_color", "PrimaryButton", UIPalette.AMBER)
	theme.set_color("font_disabled_color", "PrimaryButton", UIPalette.TEXT_FAINT)
	theme.set_stylebox("normal", "PrimaryButton",
		_pad(_outlined(_clear(), UIPalette.AMBER, 2), PX, PY))
	theme.set_stylebox("hover", "PrimaryButton",
		_pad(_outlined(UIPalette.AMBER, UIPalette.AMBER, 2), PX, PY))
	theme.set_stylebox("pressed", "PrimaryButton",
		_pad(_outlined(UIPalette.AMBER_DIM, UIPalette.AMBER_DIM, 2), PX, PY))
	# Disabled keeps the outline and loses its colour, so a Start button that
	# cannot be pressed yet is still visibly the button you are waiting on.
	theme.set_stylebox("disabled", "PrimaryButton",
		_pad(_outlined(_clear(), UIPalette.LINE, 2), PX, PY))


## Nav: the main menu's own list. **An underline, not a bar and not a box.**
##
## The old nav drew a 4 px accent bar down the left edge of a filled row, which
## worked when the menu was a vertical stack and is meaningless now that it is a
## horizontal bottom bar (unit M). Underlining the word itself is the same
## information — "this one" — in the axis the bar actually runs in, and it is
## the only decoration a row of five words needs. The box is transparent and
## square: a corner radius on a bottom-border-only stylebox rounds nothing.
static func _nav(theme: Theme) -> void:
	theme.set_type_variation("NavButton", "Button")
	theme.set_font_size("font_size", "NavButton", UIPalette.FONT_LEAD)
	theme.set_color("font_color", "NavButton", UIPalette.TEXT_DIM)
	theme.set_color("font_hover_color", "NavButton", UIPalette.TEXT)
	theme.set_color("font_focus_color", "NavButton", UIPalette.TEXT)
	theme.set_color("font_pressed_color", "NavButton", UIPalette.AMBER)
	theme.set_color("font_disabled_color", "NavButton", UIPalette.TEXT_FAINT)
	theme.set_stylebox("normal", "NavButton", _nav_underline(_clear(), 0))
	theme.set_stylebox("hover", "NavButton", _nav_underline(UIPalette.AMBER, 2))
	theme.set_stylebox("pressed", "NavButton", _nav_underline(UIPalette.AMBER, 2))
	theme.set_stylebox("focus", "NavButton", _nav_underline(UIPalette.AMBER, 2))
	theme.set_stylebox("disabled", "NavButton", _nav_underline(_clear(), 0))


static func _nav_underline(rule: Color, width: int) -> StyleBoxFlat:
	return _pad(_ruled(_clear(), rule, width, SIDE_BOTTOM, 0), 6, 13)


static func _focus_ring() -> StyleBoxFlat:
	var box := _flat(_clear())
	box.draw_center = false
	box.border_color = UIPalette.AMBER
	box.set_border_width_all(1)
	box.set_expand_margin_all(2)
	return box


# ------------------------------------------------------------------ inputs ---

## **A field the text touches the edge of is a field nobody wants to type in.**
##
## The field is a soft surface with a lit rule under it rather than a box: the
## `RAISED` wash says where you may click, the rule says it is a field and turns
## accent when it is live. The content margins are 12/8 rather than the 2 px the
## showroom's rule-only field used — the owner's one complaint about that shot
## was that the text started hard against the left edge, and on a field with no
## left border there is nothing to stop it.
static func _field(fill: Color, rule: Color) -> StyleBoxFlat:
	return _pad(_ruled(fill, rule, 1, SIDE_BOTTOM), 12, 8)


static func _inputs(theme: Theme, body: Font) -> void:
	theme.set_font("font", "LineEdit", body)
	theme.set_font_size("font_size", "LineEdit", UIPalette.FONT_BODY)
	theme.set_color("font_color", "LineEdit", UIPalette.TEXT)
	theme.set_color("font_placeholder_color", "LineEdit", UIPalette.TEXT_FAINT)
	theme.set_color("font_uneditable_color", "LineEdit", UIPalette.TEXT_DIM)
	theme.set_color("caret_color", "LineEdit", UIPalette.AMBER)
	theme.set_color("selection_color", "LineEdit", _wash(UIPalette.AMBER, 0.28))
	theme.set_stylebox("normal", "LineEdit", _field(UIPalette.RAISED, UIPalette.LINE_STRONG))
	theme.set_stylebox("focus", "LineEdit", _field(UIPalette.RAISED_STRONG, UIPalette.AMBER))
	theme.set_stylebox("read_only", "LineEdit",
		_field(UIPalette.at(UIPalette.RAISED, 0.02), UIPalette.LINE))

	# A dropdown is pressed, not typed into, so it takes the button's three
	# states rather than the field's rule.
	theme.set_font_size("font_size", "OptionButton", UIPalette.FONT_SMALL)
	theme.set_color("font_color", "OptionButton", UIPalette.TEXT)
	theme.set_color("font_hover_color", "OptionButton", UIPalette.AMBER_GLOW)
	theme.set_color("font_pressed_color", "OptionButton", UIPalette.AMBER)
	theme.set_color("font_disabled_color", "OptionButton", UIPalette.TEXT_FAINT)
	theme.set_stylebox("normal", "OptionButton", _pad(_flat(UIPalette.RAISED), 14, 8))
	theme.set_stylebox("hover", "OptionButton", _pad(_flat(UIPalette.RAISED_STRONG), 14, 8))
	theme.set_stylebox("pressed", "OptionButton", _pad(_flat(_wash()), 14, 8))
	theme.set_stylebox("disabled", "OptionButton", _pad(_flat(_clear()), 14, 8))
	theme.set_stylebox("focus", "OptionButton", _focus_ring())

	# The popup is the one surface that is nearly opaque, because it is drawn
	# over whatever it was opened from and a translucent list on top of a list
	# is unreadable. Its hover is the same accent wash as a pressed button.
	theme.set_stylebox("panel", "PopupMenu", _flat(Color(0.04, 0.045, 0.05, 0.99)))
	theme.set_stylebox("hover", "PopupMenu", _flat(_wash()))
	theme.set_color("font_color", "PopupMenu", UIPalette.TEXT)
	theme.set_color("font_hover_color", "PopupMenu", UIPalette.AMBER_GLOW)
	theme.set_font_size("font_size", "PopupMenu", UIPalette.FONT_SMALL)


static func _toggles(theme: Theme, body: Font) -> void:
	for type: String in ["CheckButton", "CheckBox"]:
		theme.set_font("font", type, body)
		theme.set_font_size("font_size", type, UIPalette.FONT_SMALL)
		theme.set_color("font_color", type, UIPalette.TEXT_DIM)
		theme.set_color("font_hover_color", type, UIPalette.TEXT)
		theme.set_color("font_pressed_color", type, UIPalette.BOG)
		for state: String in ["normal", "hover", "pressed", "disabled"]:
			theme.set_stylebox(state, type, _pad(_flat(_clear()), 4, 6))
		theme.set_stylebox("focus", type, _focus_ring())


## **A slider with an invisible track is a dial with no dial on it.**
##
## The unfilled part of the track used to be a near-black, which worked when it
## sat on a blue-grey panel and was the darker thing on it. On this scheme the
## panel *is* near-black, and the first render of the settings sheet came back
## with seven bars of yellow floating in nothing — no groove behind them, so no
## way to see how far a value had left to go. The track is now a `LINE` groove,
## the same 12% white the separators are: the one place in the UI where a
## hairline earns its keep is the one that has to be seen past the end of the
## fill.
static func _sliders(theme: Theme) -> void:
	var track := _flat(UIPalette.LINE, 3)
	track.content_margin_top = 3
	track.content_margin_bottom = 3
	theme.set_stylebox("slider", "HSlider", track)
	# The filled part of the track, at radius 4 rather than the panel's 10: a
	# bar this short is a capsule long before it reaches 10, and 3 — what it
	# used to be — is the one square thing left on a screen that has just gone
	# round everywhere.
	theme.set_stylebox("grabber_area", "HSlider", _flat(UIPalette.AMBER_DIM, 4))
	theme.set_stylebox("grabber_area_highlight", "HSlider", _flat(UIPalette.AMBER, 4))


## **A scroll bar with no width is a panel that does not say it scrolls** (D-076,
## and a Known Issue in `docs/STATUS.md` until it).
##
## These four styleboxes were all `_flat`, and a `StyleBoxFlat` with no content
## margins has a minimum size of zero. A `ScrollBar`'s thickness is exactly that
## minimum size, so the lobby's match panel — which scrolls at every window size
## the game ships at — had a bar one or two pixels wide in a colour chosen to be
## quiet. The rows past "Spear recharge" were reachable and nothing on screen
## said so; the panel read as clipped.
##
## `BAR` is the width the margins buy, and the grabber is the palette's
## `LINE_STRONG` — the same 30% white as the rule under a text field, which is
## what a hairline you are meant to *see* is worth in this scheme. Accent on
## hover and on the drag, like every other thing in this UI you can grab.
static func _scrollbars(theme: Theme) -> void:
	const BAR := 5
	for type: String in ["VScrollBar", "HScrollBar"]:
		var horizontal := type == "HScrollBar"
		var pad_x := 0 if horizontal else BAR
		var pad_y := BAR if horizontal else 0
		theme.set_stylebox("scroll", type,
			_pad(_flat(UIPalette.at(UIPalette.VOID, 0.55), 3), pad_x, pad_y))
		theme.set_stylebox("grabber", type,
			_pad(_flat(UIPalette.LINE_STRONG, 3), pad_x, pad_y))
		theme.set_stylebox("grabber_highlight", type,
			_pad(_flat(UIPalette.AMBER_DIM, 3), pad_x, pad_y))
		theme.set_stylebox("grabber_pressed", type,
			_pad(_flat(UIPalette.AMBER, 3), pad_x, pad_y))


static func _misc(theme: Theme, body: Font) -> void:
	theme.set_stylebox("panel", "ScrollContainer", StyleBoxEmpty.new())

	theme.set_font("normal_font", "RichTextLabel", body)
	theme.set_font_size("normal_font_size", "RichTextLabel", UIPalette.FONT_SMALL)
	theme.set_color("default_color", "RichTextLabel", UIPalette.TEXT_DIM)
	theme.set_stylebox("normal", "RichTextLabel", StyleBoxEmpty.new())
	theme.set_stylebox("focus", "RichTextLabel", StyleBoxEmpty.new())

	var rule := _flat(UIPalette.LINE, 0)
	rule.content_margin_top = 1
	theme.set_stylebox("separator", "HSeparator", rule)
	theme.set_constant("separation", "HSeparator", 1)

	theme.set_stylebox("background", "ProgressBar", _flat(UIPalette.at(UIPalette.VOID, 0.85), 4))
	theme.set_stylebox("fill", "ProgressBar", _flat(UIPalette.AMBER, 4))
	theme.set_color("font_color", "ProgressBar", UIPalette.TEXT_DIM)
	theme.set_font_size("font_size", "ProgressBar", UIPalette.FONT_TINY)
