extends SceneTree
## Photograph the seven props into the ability bar's tiles. Development tool,
## not shipped.
##
##     Godot --path . --script tools/bake_tiles.gd
##     Godot --path . --script tools/bake_tiles.gd -- check
##     Godot --path . --script tools/bake_tiles.gd -- sheet
##
## `check` re-measures what is already on disk and prints a verdict without
## writing anything; `sheet` writes `out/tiles_sheet.png`, the seven side by
## side on one strip, which is the only way to judge "do these read as a set"
## with an eye rather than with a number. Plain, it bakes.
##
## **Baked, not rendered at runtime** — D-003 and D-016's argument, and the way
## every other generated thing in this repo works: a `SubViewport` per tile in
## the live HUD is seven cameras and seven render targets running behind a
## fight, and what it would buy is a picture that is identical every frame. A
## PNG is diffable, is regenerated by one command, and costs the HUD a
## `draw_texture_rect`.
##
## # The framing rule
##
## One camera, one pair of lights, one bearing. **The only thing that differs
## between the seven photographs is the zoom**, and that number comes out of one
## rule rather than out of seven judgements:
##
##   the geometric mean of the silhouette's on-screen width and height
##   is `INK` of the tile's side, capped so the longer of the two never
##   passes `REACH` of it.
##
## **Why not the longest axis.** "Every prop's longest axis is the same fraction
## of the tile" is the obvious rule and it is the one that makes seven
## photographs look like seven unrelated pictures. These props are not the same
## shape: the arrow is 1.000 x 0.134 m — 7.5:1 — and the mushroom is 1.797 x
## 2.029 x 2.374 m, barely 1.2:1. Give both the same *length* and the arrow is a
## hairline ruled across an empty square while the mushroom is a solid block
## edge to edge. They would have one thing in common, and it would not be
## anything the eye reads.
##
## The geometric mean is the side of the square with the silhouette's own
## *proportions* built in, so it carries the shape's slenderness with it: a prop
## twice as slender is allowed to be √2 longer, in exact proportion, and the two
## end up occupying the same rectangle of the tile. The long ones stay visibly
## the long ones — the spear runs 2.2x the length the mushroom is wide rather
## than the same as it — and no prop is a hairline or a block.
##
## **What this equalises is the box, not the paint.** Measured off the finished
## tiles, the seven share a bounding box to within 0.002 of the side, and their
## actual inked area still runs from 4% (the arrow, a line) to 30% (the potion, a
## sphere). That is the correct answer and not a miss: a rule that gave a line
## and a sphere the same number of lit pixels would have to draw the line half
## the width of the tile thick. Slender things cover less. What a set needs is
## that they are framed alike, and they are.
##
## `REACH` is a safety rail rather than a second rule. On today's seven the ink
## budget binds every one of them and the cap never bites — the 45° roll already
## hands the slender ones √2 more room than the side. It is there for the day a
## 12:1 prop arrives and the ink rule tries to run it off both corners, and
## `check` prints which of the two bound each prop so the day it starts biting is
## visible rather than silent.
##
## **And the long ones lie on the diagonal.** Anything over `DIAGONAL_ASPECT` is
## rolled 45°, which is where `AbilitySlot`'s drawn glyphs already put the spear
## and the great sword, for a reason worth keeping: a vertical line in a square
## reads as a divider. The diagonal is also √2 longer than the side, which is
## where a long prop's extra length goes without touching a corner.
##
## **One light rig means one lighting.** Six of the seven are ordinary lit
## materials; the spear alone is D-027's black-albedo-plus-emission, which would
## come out of a lit rig flat while its six neighbours were modelled. So in this
## rig — and only in this rig — a pre-shaded emission map is used as *albedo*
## and the emission is switched off, so all seven take the same key and the same
## fill. Nothing is written back to the asset.

const SUBJECTS := ["spear", "bow", "arrow", "greatsword", "mushroom", "lure",
	"heal_potion"]
const SOURCE := "res://art/generated/%s.glb"
const OUT_DIR := "res://resources/ui/tiles"
const OUT_PATH := OUT_DIR + "/%s.png"
const SHEET_PATH := "res://out/tiles_sheet.png"

## Baked at four times the 62 px the tile is authored at, so the HUD still has a
## crisp tile on a 4K screen — `canvas_items` stretch scales the whole UI up
## from the 1600x900 base and a 62 px source would be resampled up.
const TILE := 256

## The framing budget, as fractions of the tile's side. See the header.
const INK := 0.66
const REACH := 0.88
## Over this width-to-length ratio a prop is laid on the tile's diagonal.
const DIAGONAL_ASPECT := 2.0
const DIAGONAL_ROLL := -45.0

## The one bearing. Yaw brings a face round to the light and pitch looks down on
## the prop a little, which is what gives a photograph of a flat thing any depth
## at all. Applied to the prop, not the camera, so that world XY is screen XY
## and the roll below is a screen roll.
const YAW := 34.0
const PITCH := -15.0

## What the measurements are allowed to drift by before `check` complains. The
## budget is solved exactly, so this is the render's own quantisation — a
## silhouette measured off 256 alpha pixels, against one solved from vertices.
const TOLERANCE := 0.035

var _failed := false
## Set when the last picture is written. A `SceneTree` script's `_process` ends
## the run the moment it returns true, and this one is a coroutine — without a
## flag the loop would quit on the first idle frame, before a single shot.
var _done := false


func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	var mode: String = args[0] if args.size() > 0 else "bake"
	if mode == "check":
		_check()
		quit(1 if _failed else 0)
		return
	Engine.max_fps = 60
	_run(mode)


func _run(mode: String) -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var viewport := _build_viewport()
	var images: Array[Image] = []
	var rows: Array[String] = []
	for subject: String in SUBJECTS:
		var image := await _shoot(viewport, subject, rows)
		if image == null:
			_failed = true
			continue
		images.append(image)
		if mode != "sheet":
			var err := image.save_png(OUT_PATH % subject)
			if err != OK:
				push_error("bake_tiles: could not write %s (error %d)" % [subject, err])
				_failed = true
	for row: String in rows:
		print(row)
	if mode == "sheet":
		_write_sheet(images)
	else:
		print("bake_tiles: wrote %d tiles to %s" % [images.size(), OUT_DIR])
	_verdict(rows)
	_done = true
	quit(1 if _failed else 0)


# ------------------------------------------------------------------ the rig ---

func _build_viewport() -> SubViewport:
	var viewport := SubViewport.new()
	viewport.size = Vector2i(TILE, TILE)
	# Transparent, because a tile is drawn over the slot's own dark square and a
	# baked-in background would be a second, slightly different square.
	viewport.transparent_bg = true
	viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	viewport.msaa_3d = Viewport.MSAA_4X
	root.add_child(viewport)

	var env := Environment.new()
	env.background_mode = Environment.BG_CANVAS
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	# A cool, dim ambient so the shadow side is not black. The UI's own ground
	# is a blue-cast near-black and a prop lit only from one side would read as
	# half a prop cut out of the tile.
	env.ambient_light_color = Color(0.55, 0.64, 0.78)
	env.ambient_light_energy = 0.55
	env.tonemap_mode = Environment.TONE_MAPPER_ACES
	env.tonemap_white = 3.0
	var world := WorldEnvironment.new()
	world.environment = env
	viewport.add_child(world)

	# Key, warm and high on the camera's left, because the whole UI is lit by a
	# torch and a tile lit from the other side would be the one thing in it that
	# is not. Fill, cool and low on the right, at a third of the energy.
	var key := DirectionalLight3D.new()
	key.rotation_degrees = Vector3(-38, -32, 0)
	key.light_color = Color(1.0, 0.93, 0.82)
	key.light_energy = 2.6
	viewport.add_child(key)

	var fill := DirectionalLight3D.new()
	fill.rotation_degrees = Vector3(-12, 128, 0)
	fill.light_color = Color(0.68, 0.80, 1.0)
	fill.light_energy = 0.9
	viewport.add_child(fill)

	var camera := Camera3D.new()
	camera.name = "Camera"
	camera.projection = Camera3D.PROJECTION_ORTHOGONAL
	camera.near = 0.01
	camera.far = 100.0
	viewport.add_child(camera)
	camera.make_current()
	return viewport


## One prop, framed by the rule, photographed, and its measurements appended to
## `rows`.
func _shoot(viewport: SubViewport, subject: String,
		rows: Array[String]) -> Image:
	var packed := load(SOURCE % subject) as PackedScene
	if packed == null:
		push_error("bake_tiles: missing %s" % (SOURCE % subject))
		return null
	var prop := packed.instantiate() as Node3D
	viewport.add_child(prop)
	_relight(prop)

	# The prop's own longest axis to screen-vertical first, so "aspect" below is
	# a fact about the shape rather than about how the artist happened to lay
	# the model out — the bow and the arrow are authored along X and the spear
	# and the sword along Y.
	var points := _vertices(prop)
	if points.is_empty():
		push_error("bake_tiles: %s has no vertices" % subject)
		prop.queue_free()
		return null
	var upright := _align_longest_to_up(points)
	var aspect := _aspect(points, upright)
	var roll := DIAGONAL_ROLL if aspect >= DIAGONAL_ASPECT else 0.0
	var basis := Basis(Vector3.BACK, deg_to_rad(roll)) \
		* Basis.from_euler(Vector3(deg_to_rad(PITCH), deg_to_rad(YAW), 0.0)) \
		* upright
	prop.transform = Transform3D(basis, Vector3.ZERO)

	# The silhouette, in the plane the camera sees, measured off the real
	# vertices rather than off an AABB: a thin prop laid on the diagonal has an
	# axis-aligned box half again its own size, and framing to that box is how
	# a tool ends up with a spear floating in the middle of an empty tile.
	var flat := Rect2()
	var first := true
	for point: Vector3 in points:
		var at := basis * point
		var seen := Vector2(at.x, at.y)
		if first:
			flat = Rect2(seen, Vector2.ZERO)
			first = false
		else:
			flat = flat.expand(seen)

	var mean := sqrt(flat.size.x * flat.size.y)
	var longest := maxf(flat.size.x, flat.size.y)
	var by_ink := mean / INK
	var by_reach := longest / REACH
	var ortho := maxf(by_ink, by_reach)
	var centre := flat.position + flat.size * 0.5

	var camera := viewport.get_node("Camera") as Camera3D
	camera.size = ortho
	camera.position = Vector3(centre.x, centre.y, 50.0)
	camera.rotation = Vector3.ZERO

	await process_frame
	await process_frame
	RenderingServer.force_draw()
	var image := viewport.get_texture().get_image()
	prop.queue_free()
	if image == null:
		push_error("bake_tiles: %s produced no image" % subject)
		return null

	var drawn := _measure(image)
	rows.append(("bake_tiles: %-12s aspect %4.1f:1  %-8s  mean %.3f of tile  "
		+ "longest %.3f  ink %.3f") % [subject, aspect,
		"diagonal" if roll != 0.0 else "upright",
		drawn["mean"], drawn["longest"], drawn["coverage"]])
	return image


## A copy of every material with D-027's pre-shaded emission moved to albedo.
## The spear is the only prop this touches today; it is written as a property of
## the material rather than as a special case for one file so that the next
## black-albedo asset joins the set instead of arriving flat.
func _relight(node: Node) -> void:
	for mesh: MeshInstance3D in _meshes(node):
		for surface in mesh.mesh.get_surface_count():
			var source := mesh.get_active_material(surface) as StandardMaterial3D
			if source == null or not source.emission_enabled:
				continue
			if source.albedo_color.get_luminance() > 0.02:
				continue
			var lit := source.duplicate() as StandardMaterial3D
			lit.albedo_color = Color.WHITE
			lit.albedo_texture = source.emission_texture
			lit.emission_enabled = false
			mesh.set_surface_override_material(surface, lit)


# --------------------------------------------------------------- the maths ---

## A basis that turns the prop's longest model axis into +Y.
func _align_longest_to_up(points: PackedVector3Array) -> Basis:
	var box := _bounds(points)
	var axis := 0
	if box.size.y > box.size[axis]:
		axis = 1
	if box.size.z > box.size[axis]:
		axis = 2
	match axis:
		0:
			# X to Y: a quarter turn about Z.
			return Basis(Vector3.BACK, deg_to_rad(90.0))
		2:
			# Z to Y: a quarter turn about X.
			return Basis(Vector3.RIGHT, deg_to_rad(-90.0))
		_:
			return Basis.IDENTITY


## How slender the prop is once it is standing up: its length over the wider of
## the two axes across it. This is the number that decides the diagonal, and it
## is a fact about the shape rather than about the camera.
func _aspect(points: PackedVector3Array, upright: Basis) -> float:
	var turned := PackedVector3Array()
	for point: Vector3 in points:
		turned.append(upright * point)
	var box := _bounds(turned)
	var across := maxf(maxf(box.size.x, box.size.z), 0.0001)
	return box.size.y / across


func _bounds(points: PackedVector3Array) -> AABB:
	var box := AABB(points[0], Vector3.ZERO)
	for point: Vector3 in points:
		box = box.expand(point)
	return box


## Every vertex of every mesh under the prop, in the prop's own space.
func _vertices(prop: Node3D) -> PackedVector3Array:
	var out := PackedVector3Array()
	for mesh: MeshInstance3D in _meshes(prop):
		var local := prop.global_transform.affine_inverse() * mesh.global_transform
		for point: Vector3 in mesh.mesh.get_faces():
			out.append(local * point)
	return out


func _meshes(node: Node) -> Array[MeshInstance3D]:
	var out: Array[MeshInstance3D] = []
	if node is MeshInstance3D:
		out.append(node as MeshInstance3D)
	for child in node.get_children():
		out.append_array(_meshes(child))
	return out


# ----------------------------------------------------------------- reading ---

## What actually landed on the tile: the alpha bounding box as fractions of the
## side, and what share of the tile is inked. Measured off the PNG rather than
## predicted from the solve, because the solve is the claim and this is the
## picture.
static func _measure(image: Image) -> Dictionary:
	var side := float(image.get_width())
	var left := side
	var right := -1.0
	var top := side
	var bottom := -1.0
	var inked := 0
	for y in image.get_height():
		for x in image.get_width():
			if image.get_pixel(x, y).a < 0.35:
				continue
			inked += 1
			left = minf(left, float(x))
			right = maxf(right, float(x) + 1.0)
			top = minf(top, float(y))
			bottom = maxf(bottom, float(y) + 1.0)
	if right < 0.0:
		return {"mean": 0.0, "longest": 0.0, "coverage": 0.0}
	var width := (right - left) / side
	var height := (bottom - top) / side
	return {
		"mean": sqrt(width * height),
		"longest": maxf(width, height),
		"coverage": float(inked) / (side * side),
	}


## Re-measure what is on disk. Cheap, headless-safe, and the thing the gate
## runs: the tiles are committed, so what has to be true on every machine is
## that the committed pictures obey the rule — not that a GPU can reproduce them.
func _check() -> void:
	var means: Array[float] = []
	for subject: String in SUBJECTS:
		var image := Image.load_from_file(ProjectSettings.globalize_path(
			OUT_PATH % subject))
		if image == null:
			print("bake_tiles: %s is missing" % subject)
			_failed = true
			continue
		var drawn := _measure(image)
		var bound := "reach" if drawn["longest"] >= REACH - TOLERANCE else "ink"
		var ok := true
		if drawn["longest"] > REACH + TOLERANCE:
			ok = false
		if bound == "ink" and absf(drawn["mean"] - INK) > TOLERANCE:
			ok = false
		means.append(drawn["mean"])
		print("bake_tiles: %-12s %-5s mean %.3f  longest %.3f  ink %.3f  %s"
			% [subject, bound, drawn["mean"], drawn["longest"],
			drawn["coverage"], "ok" if ok else "OUT OF BUDGET"])
		if not ok:
			_failed = true
	if means.size() == SUBJECTS.size():
		var low := means[0]
		var high := means[0]
		for value: float in means:
			low = minf(low, value)
			high = maxf(high, value)
		print("bake_tiles: mean spans %.3f..%.3f across the set (budget %.2f)"
			% [low, high, INK])
	print("bake_tiles: %s" % ("PASS" if not _failed else "FAIL"))


func _verdict(_rows: Array[String]) -> void:
	print("bake_tiles: %s" % ("FAIL" if _failed else "PASS"))


## The seven on one strip, on the slot's own dark square, so the question this
## whole file exists to answer — do they read as a set — can be looked at.
func _write_sheet(images: Array[Image]) -> void:
	if images.is_empty():
		return
	var gap := 12
	var sheet := Image.create(images.size() * TILE + (images.size() + 1) * gap,
		TILE + gap * 2, false, Image.FORMAT_RGBA8)
	sheet.fill(Color(0.02, 0.027, 0.04, 1.0))
	for i in images.size():
		var at := Vector2i(gap + i * (TILE + gap), gap)
		sheet.blend_rect(images[i], Rect2i(Vector2i.ZERO, Vector2i(TILE, TILE)), at)
	DirAccess.make_dir_recursive_absolute(
		ProjectSettings.globalize_path("res://out"))
	sheet.save_png(SHEET_PATH)
	print("bake_tiles: wrote %s" % SHEET_PATH)


func _process(_delta: float) -> bool:
	return _done
