"""Turn assets/source/clips.json into a script that fetches every clip from Mixamo.

Mixamo has no public API and no batch download, but the site's own browser calls
are plain JSON, so the fetch runs *in the browser*, in the Mixamo tab, as a pasted
console script. This file only generates that script; it never talks to Mixamo.

    python tools/mixamo_fetch.py     # writes build/mixamo_fetch.js and copies it to the clipboard

Then, in Chrome: log in at https://www.mixamo.com, make the BOG the current
character (the one shown on the right), press F12, open Console, paste, Enter.
A blank tab opens and one .fbx per row lands in Downloads, named by the row's
`file`. Chrome asks once to allow multiple downloads: say yes.

Progress is remembered in the tab's localStorage, so pasting again after a
failure resumes where it stopped; `bogFetchReset()` in the console forgets it.

Every clip is exported animation-only ("without skin": the body is BOG.fbx,
fetched once by hand as a T-pose), FBX binary, at the table's fps, with no
keyframe reduction, and in place where the row asks for it. If Mixamo refuses
in-place for a clip, the script fetches it with its travel and says so; the
import step strips travel anyway.
"""
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TABLE = ROOT / "assets" / "source" / "clips.json"
OUT = ROOT / "build" / "mixamo_fetch.js"

TEMPLATE = r"""// Generated by tools/mixamo_fetch.py from assets/source/clips.json. Do not edit.
// Paste into the Chrome console on https://www.mixamo.com with the BOG selected.
(async () => {
  const CLIPS = __CLIPS__;
  const FPS = "__FPS__";
  const BASE = 'https://www.mixamo.com/api/v1';
  const H = {
    'Accept': 'application/json', 'Content-Type': 'application/json',
    'Authorization': `Bearer ${localStorage.access_token}`,
    'X-Api-Key': 'mixamo2', 'X-Requested-With': 'XMLHttpRequest',
  };
  const api = async (url, init = {}) => {
    const r = await fetch(url, { ...init, headers: H });
    if (!r.ok && r.status !== 202) throw new Error(`HTTP ${r.status} for ${url}`);
    return r.json();
  };
  const sleep = (ms) => new Promise((res) => setTimeout(res, ms));

  const prim = await api(`${BASE}/characters/primary`);
  const cid = prim.primary_character_id;
  console.log('character:', prim.primary_character_name, cid);
  if (!/bog/i.test(prim.primary_character_name || '')) {
    console.error('The selected character is not the BOG. Pick it in Mixamo, then paste again.');
    return;
  }
  const doneKey = `bog_fetch_done_${cid}`;
  const done = new Set(JSON.parse(localStorage.getItem(doneKey) || '[]'));
  const sig = (clip) => `${clip.file}|${clip.inplace ? 'inplace' : 'travel'}`;
  window.bogFetchReset = () => { localStorage.removeItem(doneKey); console.log('progress forgotten'); };
  const tab = window.open('', '_blank');
  if (!tab) { console.error('Popup blocked: allow popups for mixamo.com and paste again.'); return; }

  // A row with a query instead of an id becomes one row per search result.
  const known = new Set(CLIPS.filter((c) => c.id).map((c) => c.id));
  const camel = (s) => s.replace(/(^|[^A-Za-z0-9]+)([a-z0-9])/g, (_, __, ch) => ch.toUpperCase()).replace(/[^A-Za-z0-9]/g, '');
  const expanded = [];
  for (const clip of CLIPS) {
    if (clip.id) { expanded.push(clip); continue; }
    const q = encodeURIComponent(clip.query);
    const res = await api(`${BASE}/products?page=1&limit=96&order=&type=Motion&query=${q}`);
    const hits = (res.results || []).filter((r) => !known.has(r.id) && !r.description.includes(','))
      .filter((r) => !clip.keep || clip.keep.includes(r.description));
    console.log(`search "${clip.query}": ${hits.length} clips`, hits.map((r) => r.description));
    for (const r of hits)
      expanded.push({ file: `${clip.file}-${camel(r.description)}`, id: r.id, name: r.description, inplace: clip.inplace });
  }

  // The monitor reports the latest job for the character, so note what it says
  // before each export and wait until it says something new.
  const monitor = () => api(`${BASE}/characters/${cid}/monitor`).catch(() => ({}));
  const exportOne = async (clip, inplace) => {
    const p = await api(`${BASE}/products/${clip.id}?similar=0&character_id=${cid}`);
    if (p.description !== clip.name)
      console.warn(`${clip.file}: table says "${clip.name}", Mixamo says "${p.description}"`);
    const g = p.details.gms_hash;
    const gms = { ...g, params: (g.params || []).map((x) => x[1]).join(','), inplace, overdrive: 0 };
    const before = (await monitor()).job_result || null;
    await api(`${BASE}/animations/export`, {
      method: 'POST',
      body: JSON.stringify({
        character_id: cid, gms_hash: [gms], product_name: clip.file, type: p.type || 'Motion',
        preferences: { format: 'fbx7_2019', skin: 'false', fps: FPS, reducekf: '0' },
      }),
    });
    for (let i = 0; i < 120; i++) {
      await sleep(1500);
      const m = await monitor();
      if (m.status === 'completed' && m.job_result && m.job_result !== before) return m.job_result;
      if (m.status === 'failed') throw new Error(`export failed: ${JSON.stringify(m)}`);
    }
    throw new Error('timed out waiting for the export');
  };

  let n = 0;
  const failed = [];
  for (const clip of expanded) {
    if (done.has(sig(clip))) { console.log('already fetched:', clip.file); continue; }
    try {
      let url;
      try {
        url = await exportOne(clip, clip.inplace);
      } catch (e) {
        if (!clip.inplace) throw e;
        console.warn(`${clip.file}: in-place refused (${e.message}); fetching with travel`);
        url = await exportOne(clip, false);
      }
      tab.location.href = url;
      n += 1;
      done.add(sig(clip));
      localStorage.setItem(doneKey, JSON.stringify([...done]));
      console.log(`${n}/${expanded.length} ${clip.file}`);
      await sleep(3000);
    } catch (e) {
      console.error('FAILED', clip.file, e);
      failed.push(clip.file);
    }
  }
  console.log(`finished: ${n} fetched this run, ${failed.length} failed`, failed);
  console.log('Move the .fbx files from Downloads into assets/source/anims/.');
})();
"""


def main():
    table = json.loads(TABLE.read_text())
    # A row marked `mixamo_by_hand` was downloaded from the site by hand rather
    # than through this script, so nothing here knows its catalogue id — Mixamo
    # names every exported take "mixamo.com" and puts the exporter's temp path
    # in the file name field, so the animation's own name is not in the .fbx to
    # be read back out. Such a row is skipped rather than sent over with a null
    # id, which the browser half would turn into a search for "undefined". It is
    # named on the way past so the skip is visible rather than silent.
    #
    # A `mirror_of` row is skipped for a different reason and silently: it has
    # no take to fetch at all, being the reflection of another row built at
    # import (D-071, D-098).
    by_hand = [c["file"] for c in table["clips"] if c.get("mixamo_by_hand")]
    clips = [
        {"file": c["file"], "id": c.get("mixamo_id"), "name": c.get("mixamo_name"),
         "query": c.get("mixamo_query"), "keep": c.get("mixamo_keep"), "inplace": c["in_place"]}
        for c in table["clips"]
        if not c.get("mixamo_by_hand") and not c.get("mirror_of")
    ]
    js = TEMPLATE.replace("__CLIPS__", json.dumps(clips, indent=2)).replace("__FPS__", str(table["fps"]))
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(js)
    print(f"{len(clips)} clips -> {OUT}")
    for name in by_hand:
        print(f"  fetched by hand, not in the script: {name}")
    if sys.platform == "win32":
        subprocess.run("clip", input=js.encode("utf-16-le"), check=False)
        print("copied to the clipboard")


if __name__ == "__main__":
    main()
